### ISSUE TITLE
JSON-awareness in message key

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk-package-kafka#107]
It would be useful to introduce (optional) JSON-awareness when passing message keys - similar to `isJSONData` (call it `isJSONKey`?).

**Comment by bjustin-ibm** [comment]
@glikson Thanks for the suggestion!

My understanding is that message keys are typically used to ensure order of consumption in topics that have more than one partition - since messages with the same key always go to the same partition. With that in mind, the usefulness of the key is not so much in the actual value, but rather in the uniqueness of that value.

As such, putting JSON data in the message key doesn't _seem_ like a common enough scenario to warrant adding this option.

Let's put this one on the shelf for now and revisit it if there are more requests for this.
